name: XGD Collaborative
favicon: null
layout_spectrum: 0.850117901340127
typography_spectrum: 0.3460864541120827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.24083105917088687
  lightness: 0.7733719954267144
  saturation: 0.696465355111286
  rhythmicContrast: 0.5727265195455402
purpose: []
